# suppressMessages(suppressWarnings(library(shinyjs)))
# suppressMessages(suppressWarnings(library(shinyalert)))
# suppressMessages(suppressWarnings(library(bsplus)))
# suppressMessages(suppressWarnings(library(upsetjs)))
# suppressMessages(suppressWarnings(library(stringr)))
# suppressMessages(suppressWarnings(library(httr)))
# suppressMessages(suppressWarnings(library(httpuv)))
# suppressMessages(suppressWarnings(library(curl)))
# suppressMessages(suppressWarnings(library(jsonlite)))
# suppressMessages(suppressWarnings(library(gprofiler2)))
# suppressMessages(suppressWarnings(library(WebGestaltR)))
# suppressMessages(suppressWarnings(library(poolr)))
suppressMessages(suppressWarnings(library(shinydashboard)))
suppressMessages(suppressWarnings(library(shinyWidgets)))
suppressMessages(suppressWarnings(library(DT)))
suppressMessages(suppressWarnings(library(tidyr)))
suppressMessages(suppressWarnings(library(enrichR))) # must be loaded for setEnrichrSite() to work
suppressMessages(suppressWarnings(library(plotly)))
suppressMessages(suppressWarnings(library(igraph)))
suppressMessages(suppressWarnings(library(visNetwork)))
